name: Test

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'    
    - uses: mpi4py/setup-mpi@v1
    - run: pip install mpi4py
    - run: python -c "import mpi4py"
