name: Test

on:
  push:

jobs:
  test:
    name: temp test
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - run: pip install uv
    - run: |
        uv venv /venv-test-x86_64 --python=python
        uv pip install --python-platform x86_64-apple-darwin -v numpy
