name: Test

on:
  push:

jobs:
  test:
    name: test windows wheel
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - run: pip install netCDF4
    - run: python -m "import netCDF4"
